# Copyright

<PRE>
Jelen Jupyter notebook a Budapesti Műszaki és Gazdaságtudományi Egyetemen tartott "Deep Learning a gyakorlatban Python és LUA alapon" tantárgy segédanyagaként készült. 
A tantárgy honlapja: http://smartlab.tmit.bme.hu/oktatas-deep-learning
Deep Learning kutatás: http://smartlab.tmit.bme.hu/deep-learning

A notebook bármely részének újra felhasználása, publikálása csak a szerzők írásos beleegyezése esetén megegengedett.

2019 (c) Gyires-Tóth Bálint (toth.b kukac tmit pont bme pont hu)
</PRE>

# Pandas csomag

Az adatok betöltésének és előfeldolgozásának egyik elsődleges eszköze Python nyelven a Pandas csomag. Készségszintű használata minden adattudós és deep learning szakember számára abszolút szükséges. A Pandas csomag betöltése a következőképp történik:

In [1]:
import pandas as pd

# A legfontosabb funkciók bemutatása példán keresztül

A Pandas legfontosabb funkcióit egy példán keresztül mutatjuk be. A példa során a Kaggle "IMDB 5000 Movie Dataset" adatbázisát fogjuk előkészíteni gépi tanuló algoritmusok számára. Ehhez először töltsük le az adatbázis CSV (Comma Separated Values, magyarul csévé) formátumát az alábbi linkről: https://www.kaggle.com/carolzhangdc/imdb-5000-movie-dataset

(Amennyiben problémába ütköztök, innen is le tudjátok tölteni: http://leszped.tmit.bme.hu/dl/movie_metadata.csv, mely eredeti forrása a fenti Kaggle oldal.)

Ez követően töltsük be az adatbázist és nézzük meg az elejét és végét:

In [2]:
df = pd.read_csv("movie_metadata.csv", sep=',')

In [3]:
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

In [4]:
df.tail()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,...,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
5038,Color,Scott Smith,1.0,87.0,2.0,318.0,Daphne Zuniga,637.0,NaN,Comedy|Drama,...,6.0,English,Canada,NaN,NaN,2013.0,470.0,7.7,NaN,84
5039,Color,NaN,43.0,43.0,NaN,319.0,Valorie Curry,841.0,NaN,Crime|Drama|Mystery|Thriller,...,359.0,English,USA,TV-14,NaN,NaN,593.0,7.5,16.00,32000
5040,Color,Benjamin Roberds,13.0,76.0,0.0,0.0,Maxwell Moody,0.0,NaN,Drama|Horror|Thriller,...,3.0,English,USA,NaN,1400.0,2013.0,0.0,6.3,NaN,16
5041,Color,Daniel Hsia,14.0,100.0,0.0,489.0,Daniel Henney,946.0,10443.0,Comedy|Drama|Romance,...,9.0,English,USA,PG-13,NaN,2012.0,719.0,6.3,2.35,660
5042,Color,Jon Gunn,43.0,90.0,16.0,16.0,Brian Herzlinger,86.0,85222.0,Documentary,...,84.0,English,USA,PG,1100.0,2004.0,23.0,6.6,1.85,456

Mivel túl sok oszlopa ("tulajdonsága", "feature"-e) van az adatbázisnak, ezért nem látjuk az összes oszlopot. Állítsuk be a Pandas-ban, hogy ezeket is jelenítse meg:

In [5]:
pd.set_option("max_columns",None)
df.head()

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
4,NaN,Doug Walker,NaN,NaN,131.0,NaN,Rob Walker,131.0,NaN,Documentary,Doug Walker,Star Wars: Episode VII - The Force Awakens ...,8,143,NaN,0.0,NaN,http://www.imdb.com/title/tt5289954/?ref_=fn_t...,NaN,NaN,NaN,NaN,NaN,NaN,12.0,7.1,NaN,0

## Hiányzó értékek kezelése

Ahogy a fenti táblában is láthatjuk, a Pandas NaN-al jelöli meg azokat a mezőket, ahova nem tartozik érték. Ezt még szoktuk null-nak, na-nak, vagy None-nak is hívni. Ezek helyettesítésével nagyon óvatosan kell bánnunk, hiszen ezek a későbbi gépi tanuló modellünket "torzítani" tudják. Például nem mindegy, hogy a hiányzó évszámokat 0-val, az évszámok átlagával, vagy pl. idei év - 5-el helyettesítjük. 
Ha sok adatunk van, és az adatstruktúrából adódóan megengedhető, akkor a legbiztosabb, ha minden olyan sort eldobunk, amiben NaN érték van. Ezt a gyakorlatban azonban szinte sosem tudjuk megtenni. Most mégis, menjünk így tovább.
Előbb nézzük meg, hogy hány ilyen sor van:

In [6]:
print ("%d (sorok, amiben van NaN) / %d (összes)" % (len(df[df.isnull().any(axis=1)]), len(df)))
# a df.isnull() az eredetivel azonos méretű táblát ad vissza, mely celláiban booleanok mutatják, hogy NaN-e az érték, vagy nem.
# az .any(axis=1) ebből soronként (az axis=1 miatt) vizsgálja meg, hogy bármelyik érték NaN-e.

1287 (sorok, amiben van NaN) / 5043 (összes)

Majd tartsuk csak meg azokat, melyekben egyáltalán nincs NaN:

In [7]:
df = df[~df.isnull().any(axis=1)] # a ~ jel a negálás operátor, ami működik DataFrame szinten is.
print("Új hossz: ", len(df))

Új hossz:  3756

*Megjegyzés: több lehetőség is van a változók megjelenítésére a print fügvénnyel, ezekről bővebben itt lehet olvasni: https://pyformat.info/*

## Kategorikus változók

A gépi tanuló eljárások számára jó, ha a kategórikus változókat külön kezeljük a numerikus változóktól. Ilyen például az, hogy a film színes vagy feketefehér. Ahhoz, hogy melyek a kategorikus változók, nézzünk bele ismét a DataFrame-be:

In [8]:
df.head(5)

,color,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,language,country,content_rating,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes
0,Color,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,English,USA,PG-13,237000000.0,2009.0,936.0,7.9,1.78,33000
1,Color,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,English,USA,PG-13,300000000.0,2007.0,5000.0,7.1,2.35,0
2,Color,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,English,UK,PG-13,245000000.0,2015.0,393.0,6.8,2.35,85000
3,Color,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,English,USA,PG-13,250000000.0,2012.0,23000.0,8.5,2.35,164000
5,Color,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,English,USA,PG-13,263700000.0,2012.0,632.0,6.6,2.35,24000

"Első ránézésre" az alábbi tulajdonságok tűnnek kategórikus változóknak: 

    color
    director_name
    actor_1_name
    actor_2_name
    actor_3_name
    language
    country
    content_rating

további feldolgozást kíván, de kategorikus változót lehet belőle csinálni: 

    genres
    plot_keywords
    
Vizsgáljuk meg ezeket részletesebben:

In [9]:
categorical_features = ["color","director_name","actor_1_name","actor_2_name","actor_3_name","language","country","content_rating"]
n_items = len(df)
for feat in categorical_features:
    print("A %s feldolgozása. Egyedi mezők száma: %d" % (feat, df[feat].nunique()))
    if df[feat].nunique()<50: # ha kezelhető mennyiségű, kiírjuk ezeket
        print(df[feat].unique())
        print("Az egyedi értékek darabszáma:")
        print(df.groupby(feat).count().iloc[:,0]) # a feat-ra csoportosítunk, majd megszámoljuk, hogy hány elem van a csoportban, és kiválasztjuk az iloc-al az első oszlopot (hiszen minden oszlopba beleírta ezt az értéket)
        # összevonjuk azokat a kategóriákat, ahol az össz darabszám kevesebb, mint 2% található
        for feat_value in df[feat].unique():
            if (len(df[df[feat]==feat_value]) / n_items <= 0.02):
                print("A %s kategória hozzáadása az OTHER kategóriához." % feat_value)
                df[feat] = df[feat].apply(lambda x: "OTHER" if x==feat_value else x, 1)
                
        print("Az egyedi értékek végső darabszáma:")
        print(df.groupby(feat).count().iloc[:,0]) # a feat-ra csoportosítunk, majd megszámoljuk, hogy hány elem van a csoportban, és kiválasztjuk az iloc-al az első oszlopot (hiszen minden oszlopba beleírta ezt az értéket)
        print("\n")

A color feldolgozása. Egyedi mezők száma: 2
['Color' ' Black and White']
Az egyedi értékek darabszáma:
color
 Black and White     124
Color               3632
Name: director_name, dtype: int64
Az egyedi értékek végső darabszáma:
color
 Black and White     124
Color               3632
Name: director_name, dtype: int64


A director_name feldolgozása. Egyedi mezők száma: 1659
A actor_1_name feldolgozása. Egyedi mezők száma: 1428
A actor_2_name feldolgozása. Egyedi mezők száma: 2188
A actor_3_name feldolgozása. Egyedi mezők száma: 2587
A language feldolgozása. Egyedi mezők száma: 34
['English' 'Mandarin' 'Aboriginal' 'Spanish' 'French' 'Filipino' 'Maya'
 'Kazakh' 'Cantonese' 'Japanese' 'Aramaic' 'Italian' 'Dutch' 'Dari'
 'German' 'Mongolian' 'Thai' 'Bosnian' 'Korean' 'Hungarian' 'Hindi'
 'Danish' 'Portuguese' 'Norwegian' 'Czech' 'Russian' 'None' 'Zulu'
 'Hebrew' 'Arabic' 'Vietnamese' 'Indonesian' 'Romanian' 'Persian']
Az egyedi értékek darabszáma:
language
Aboriginal       2
Arabic           1
Aramaic          1
Bosnian          1
Cantonese        7
Czech            1
Danish           3
Dari             2
Dutch            3
English       3598
Filipino         1
French          34
German          10
Hebrew           1
Hindi            5
Hungarian        1
Indonesian       2
Italian          7
Japanese        10
Kazakh           1
Korean           5
Mandarin        15
Maya             1
Mongolian        1
None             1
Norwegian        4
Persian          3
Portuguese       5
Romanian         1
Russian          1
Spanish         23
Thai             3
Vietnamese       1
Zulu             1
Name: color, dtype: int64
A Mandarin kategória hozzáadása az OTHER kategóriához.
A Aboriginal kategória hozzáadása az OTHER kategóriához.
A Spanish kategória hozzáadása az OTHER kategóriához.
A French kategória hozzáadása az OTHER kategóriához.
A Filipino kategória hozzáadása az OTHER kategóriához.
A Maya kategória hozzáadása az OTHER kategóriához.
A Kazakh kategória hozzáadása az OTHER kategóriához.
A Cantonese kategória hozzáadása az OTHER kategóriához.
A Japanese kategória hozzáadása az OTHER kategóriához.
A Aramaic kategória hozzáadása az OTHER kategóriához.
A Italian kategória hozzáadása az OTHER kategóriához.
A Dutch kategória hozzáadása az OTHER kategóriához.
A Dari kategória hozzáadása az OTHER kategóriához.
A German kategória hozzáadása az OTHER kategóriához.
A Mongolian kategória hozzáadása az OTHER kategóriához.
A Thai kategória hozzáadása az OTHER kategóriához.
A Bosnian kategória hozzáadása az OTHER kategóriához.
A Korean kategória hozzáadása az OTHER kategóriához.
A Hungarian kategória hozzáadása az OTHER kategóriához.
A Hindi kategória hozzáadása az OTHER kategóriához.
A Danish kategória hozzáadása az OTHER kategóriához.
A Portuguese kategória hozzáadása az OTHER kategóriához.
A Norwegian kategória hozzáadása az OTHER kategóriához.
A Czech kategória hozzáadása az OTHER kategóriához.
A Russian kategória hozzáadása az OTHER kategóriához.
A None kategória hozzáadása az OTHER kategóriához.
A Zulu kategória hozzáadása az OTHER kategóriához.
A Hebrew kategória hozzáadása az OTHER kategóriához.
A Arabic kategória hozzáadása az OTHER kategóriához.
A Vietnamese kategória hozzáadása az OTHER kategóriához.
A Indonesian kategória hozzáadása az OTHER kategóriához.
A Romanian kategória hozzáadása az OTHER kategóriához.
A Persian kategória hozzáadása az OTHER kategóriához.
Az egyedi értékek végső darabszáma:
language
English    3598
OTHER       158
Name: color, dtype: int64


A country feldolgozása. Egyedi mezők száma: 45
['USA' 'UK' 'New Zealand' 'Canada' 'Australia' 'Germany' 'China'
 'New Line' 'France' 'Japan' 'Spain' 'Hong Kong' 'Czech Republic' 'Peru'
 'South Korea' 'Aruba' 'Denmark' 'Ireland' 'South Africa' 'Italy'
 'Romania' 'Chile' 'Netherlands' 'Hungary' 'Russia' 'Belgium' 'Greece'
 'Taiwan' 'Official site' 'Thailand' 'Iran' 'West Germany' 'Georgia'
 'India' 'Mexico' 'Brazil' 'Finland' 'Norway' 'Iceland' 'Argentina'
 'Colombia' 'Poland' 'Israel' 'Indonesia' 'Afghanistan']
Az egyedi értékek darabszáma:
country
Afghanistan          1
Argentina            3
Aruba                1
Australia           39
Belgium              1
Brazil               5
Canada              59
Chile                1
China               13
Colombia             1
Czech Republic       3
Denmark              8
Finland              1
France             101
Georgia              1
Germany             80
Greece               1
Hong Kong           13
Hungary              2
Iceland              1
India                5
Indonesia            1
Iran                 4
Ireland              7
Israel               1
Italy               11
Japan               15
Mexico               6
Netherlands          3
New Line             1
New Zealand         11
Norway               4
Official site        1
Peru                 1
Poland               1
Romania              2
Russia               3
South Africa         3
South Korea          8
Spain               21
Taiwan               2
Thailand             4
UK                 318
USA               2987
West Germany         1
Name: color, dtype: int64
A New Zealand kategória hozzáadása az OTHER kategóriához.
A Canada kategória hozzáadása az OTHER kategóriához.
A Australia kategória hozzáadása az OTHER kategóriához.
A China kategória hozzáadása az OTHER kategóriához.
A New Line kategória hozzáadása az OTHER kategóriához.
A Japan kategória hozzáadása az OTHER kategóriához.
A Spain kategória hozzáadása az OTHER kategóriához.
A Hong Kong kategória hozzáadása az OTHER kategóriához.
A Czech Republic kategória hozzáadása az OTHER kategóriához.
A Peru kategória hozzáadása az OTHER kategóriához.
A South Korea kategória hozzáadása az OTHER kategóriához.
A Aruba kategória hozzáadása az OTHER kategóriához.
A Denmark kategória hozzáadása az OTHER kategóriához.
A Ireland kategória hozzáadása az OTHER kategóriához.
A South Africa kategória hozzáadása az OTHER kategóriához.
A Italy kategória hozzáadása az OTHER kategóriához.
A Romania kategória hozzáadása az OTHER kategóriához.
A Chile kategória hozzáadása az OTHER kategóriához.
A Netherlands kategória hozzáadása az OTHER kategóriához.
A Hungary kategória hozzáadása az OTHER kategóriához.
A Russia kategória hozzáadása az OTHER kategóriához.
A Belgium kategória hozzáadása az OTHER kategóriához.
A Greece kategória hozzáadása az OTHER kategóriához.
A Taiwan kategória hozzáadása az OTHER kategóriához.
A Official site kategória hozzáadása az OTHER kategóriához.
A Thailand kategória hozzáadása az OTHER kategóriához.
A Iran kategória hozzáadása az OTHER kategóriához.
A West Germany kategória hozzáadása az OTHER kategóriához.
A Georgia kategória hozzáadása az OTHER kategóriához.
A India kategória hozzáadása az OTHER kategóriához.
A Mexico kategória hozzáadása az OTHER kategóriához.
A Brazil kategória hozzáadása az OTHER kategóriához.
A Finland kategória hozzáadása az OTHER kategóriához.
A Norway kategória hozzáadása az OTHER kategóriához.
A Iceland kategória hozzáadása az OTHER kategóriához.
A Argentina kategória hozzáadása az OTHER kategóriához.
A Colombia kategória hozzáadása az OTHER kategóriához.
A Poland kategória hozzáadása az OTHER kategóriához.
A Israel kategória hozzáadása az OTHER kategóriához.
A Indonesia kategória hozzáadása az OTHER kategóriához.
A Afghanistan kategória hozzáadása az OTHER kategóriához.
Az egyedi értékek végső darabszáma:
country
France      101
Germany      80
OTHER       270
UK          318
USA        2987
Name: color, dtype: int64


A content_rating feldolgozása. Egyedi mezők száma: 12
['PG-13' 'PG' 'G' 'R' 'Approved' 'NC-17' 'X' 'Not Rated' 'Unrated' 'M'
 'GP' 'Passed']
Az egyedi értékek darabszáma:
content_rating
Approved       17
G              87
GP              1
M               2
NC-17           6
Not Rated      34
PG            566
PG-13        1308
Passed          3
R            1700
Unrated        22
X              10
Name: color, dtype: int64
A Approved kategória hozzáadása az OTHER kategóriához.
A NC-17 kategória hozzáadása az OTHER kategóriához.
A X kategória hozzáadása az OTHER kategóriához.
A Not Rated kategória hozzáadása az OTHER kategóriához.
A Unrated kategória hozzáadása az OTHER kategóriához.
A M kategória hozzáadása az OTHER kategóriához.
A GP kategória hozzáadása az OTHER kategóriához.
A Passed kategória hozzáadása az OTHER kategóriához.
Az egyedi értékek végső darabszáma:

content_rating
G          87
OTHER      95
PG        566
PG-13    1308
R        1700
Name: color, dtype: int64

Látjuk, hogy a color, language és content_rating esetén könnyű a dolgunk, ezeket un. one-hot vektorokká alakítjuk a Pandas következő függvényével:

In [10]:
df = pd.get_dummies(df, columns=["color","language","country","content_rating"])

In [11]:
df.head()

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,color_ Black and White,color_Color,language_English,language_OTHER,country_France,country_Germany,country_OTHER,country_UK,country_USA,content_rating_G,content_rating_OTHER,content_rating_PG,content_rating_PG-13,content_rating_R
0,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000,0,1,1,0,0,0,0,0,1,0,0,0,1,0
1,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0
2,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000,0,1,1,0,0,0,0,1,0,0,0,0,1,0
3,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,1,1,0,0,0,0,0,1,0,0,0,1,0
5,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,263700000.0,2012.0,632.0,6.6,2.35,24000,0,1,1,0,0,0,0,0,1,0,0,0,1,0

### Genres és plot_keywords tulajdonságok

Ezekben az esetekben előbb szét kell bontanunk a |-al elválasztott stringeket szavakra, és ezek számosságát kell megvizsgálnunk.

In [12]:
genres = pd.Series()

for value in df['genres']:
    genres = genres.append(pd.Series(value.split("|")), ignore_index=True)
    
genres = genres.drop_duplicates()
print(genres)

0             Action
1          Adventure
2            Fantasy
3             Sci-Fi
9           Thriller
17           Romance
19         Animation
20            Comedy
21            Family
23           Musical
31           Mystery
45           Western
73             Drama
74           History
140            Sport
153            Crime
157           Horror
388              War
394        Biography
934            Music
1773     Documentary
10574      Film-Noir
dtype: object

Szerencsére ez kezelhető mennyiségű kategória. Ennyi új tulajdonságot fogunk létrehozni a DateFrame-ünkben, és soronként 1-re állítjuk, amelyik szerepel a Genres-ben, és 0-ra, amelyik nem.

In [13]:
for feat in genres:
    df[feat] = 0 # minden sornál nullára állítjuk az értékeket
    df[feat] = df['genres'].apply(lambda x: 1 if feat in str(x) else 0, 1)
    print("%s típusú filmek száma:\t %d / %d" % (feat,len(df[df[feat]==1]), len(df)))

Action típusú filmek száma:	 959 / 3756
Adventure típusú filmek száma:	 781 / 3756
Fantasy típusú filmek száma:	 507 / 3756
Sci-Fi típusú filmek száma:	 496 / 3756
Thriller típusú filmek száma:	 1117 / 3756
Romance típusú filmek száma:	 859 / 3756
Animation típusú filmek száma:	 196 / 3756
Comedy típusú filmek száma:	 1461 / 3756
Family típusú filmek száma:	 442 / 3756
Musical típusú filmek száma:	 96 / 3756
Mystery típusú filmek száma:	 384 / 3756
Western típusú filmek száma:	 59 / 3756
Drama típusú filmek száma:	 1893 / 3756
History típusú filmek száma:	 149 / 3756
Sport típusú filmek száma:	 148 / 3756
Crime típusú filmek száma:	 709 / 3756
Horror típusú filmek száma:	 392 / 3756
War típusú filmek száma:	 152 / 3756
Biography típusú filmek száma:	 239 / 3756
Music típusú filmek száma:	 233 / 3756
Documentary típusú filmek száma:	 45 / 3756
Film-Noir típusú filmek száma:	 1 / 3756

In [14]:
df.head()

,director_name,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_2_name,actor_1_facebook_likes,gross,genres,actor_1_name,movie_title,num_voted_users,cast_total_facebook_likes,actor_3_name,facenumber_in_poster,plot_keywords,movie_imdb_link,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,color_ Black and White,color_Color,language_English,language_OTHER,country_France,country_Germany,country_OTHER,country_UK,country_USA,content_rating_G,content_rating_OTHER,content_rating_PG,content_rating_PG-13,content_rating_R,Action,Adventure,Fantasy,Sci-Fi,Thriller,Romance,Animation,Comedy,Family,Musical,Mystery,Western,Drama,History,Sport,Crime,Horror,War,Biography,Music,Documentary,Film-Noir
0,James Cameron,723.0,178.0,0.0,855.0,Joel David Moore,1000.0,760505847.0,Action|Adventure|Fantasy|Sci-Fi,CCH Pounder,Avatar,886204,4834,Wes Studi,0.0,avatar|future|marine|native|paraplegic,http://www.imdb.com/title/tt0499549/?ref_=fn_t...,3054.0,237000000.0,2009.0,936.0,7.9,1.78,33000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,Gore Verbinski,302.0,169.0,563.0,1000.0,Orlando Bloom,40000.0,309404152.0,Action|Adventure|Fantasy,Johnny Depp,Pirates of the Caribbean: At World's End,471220,48350,Jack Davenport,0.0,goddess|marriage ceremony|marriage proposal|pi...,http://www.imdb.com/title/tt0449088/?ref_=fn_t...,1238.0,300000000.0,2007.0,5000.0,7.1,2.35,0,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,Sam Mendes,602.0,148.0,0.0,161.0,Rory Kinnear,11000.0,200074175.0,Action|Adventure|Thriller,Christoph Waltz,Spectre,275868,11700,Stephanie Sigman,1.0,bomb|espionage|sequel|spy|terrorist,http://www.imdb.com/title/tt2379713/?ref_=fn_t...,994.0,245000000.0,2015.0,393.0,6.8,2.35,85000,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,Christopher Nolan,813.0,164.0,22000.0,23000.0,Christian Bale,27000.0,448130642.0,Action|Thriller,Tom Hardy,The Dark Knight Rises,1144337,106759,Joseph Gordon-Levitt,0.0,deception|imprisonment|lawlessness|police offi...,http://www.imdb.com/title/tt1345836/?ref_=fn_t...,2701.0,250000000.0,2012.0,23000.0,8.5,2.35,164000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,Andrew Stanton,462.0,132.0,475.0,530.0,Samantha Morton,640.0,73058679.0,Action|Adventure|Sci-Fi,Daryl Sabara,John Carter,212204,1873,Polly Walker,1.0,alien|american civil war|male nipple|mars|prin...,http://www.imdb.com/title/tt0401729/?ref_=fn_t...,738.0,263700000.0,2012.0,632.0,6.6,2.35,24000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0

## Outlierek keresése

A gépi tanuló algoritmusok számára gyakran problémát jelentenek az ún. outlierek az adatban. Ezek lehetnek a folyamatból adódó outlierek (anomáliák), de lehetnek adatbázis hibák is. Most a következőképp keressük ezeket: ha a várható érték +/- szórás háromszorosánál kisebb vagy nagyobb érték van az adatbázisban, akkor azt a szélsőértékkel helyettesítjük:

In [15]:
import numpy as np

numeric_features = ['num_critic_for_reviews', 
                    'duration',
                    'director_facebook_likes', 
                    'actor_3_facebook_likes', 
                    'actor_1_facebook_likes', 
                    'gross', 
                    'num_voted_users', 
                    'cast_total_facebook_likes',
                    'facenumber_in_poster', 
                    'num_user_for_reviews', 
                    'budget',
                    'title_year', 
                    'actor_2_facebook_likes', 
                    'imdb_score', 
                    'aspect_ratio',
                    'movie_facebook_likes',
                   ]

for feat in numeric_features:
    print("Az outlierek száma a %s tulajdonságban: %d" % (feat, len(df[ abs(df[feat] - np.mean(df[feat])) >3*np.std(df[feat])])))
    df[feat]= df[feat].apply(lambda x: np.mean(df[feat])+3*np.std(df[feat]) if x > np.mean(df[feat])+3*np.std(df[feat]) else x, 1)
    df[feat]= df[feat].apply(lambda x: np.mean(df[feat])-3*np.std(df[feat]) if x < np.mean(df[feat])-3*np.std(df[feat]) else x, 1)

Az outlierek száma a num_critic_for_reviews tulajdonságban: 58
Az outlierek száma a duration tulajdonságban: 54
Az outlierek száma a director_facebook_likes tulajdonságban: 164
Az outlierek száma a actor_3_facebook_likes tulajdonságban: 95
Az outlierek száma a actor_1_facebook_likes tulajdonságban: 12
Az outlierek száma a gross tulajdonságban: 82
Az outlierek száma a num_voted_users tulajdonságban: 77
Az outlierek száma a cast_total_facebook_likes tulajdonságban: 37
Az outlierek száma a facenumber_in_poster tulajdonságban: 66
Az outlierek száma a num_user_for_reviews tulajdonságban: 79
Az outlierek száma a budget tulajdonságban: 7
Az outlierek száma a title_year tulajdonságban: 59
Az outlierek száma a actor_2_facebook_likes tulajdonságban: 72
Az outlierek száma a imdb_score tulajdonságban: 33
Az outlierek száma a aspect_ratio tulajdonságban: 1
Az outlierek száma a movie_facebook_likes tulajdonságban: 85

## Felesleges oszlopok törlése

Részben a feldolgozás miatt, részben pedig mert nem fogjuk használni, néhány oszlopot törlünk - így memóriát szabadítva fel. Természetesen ezeken a tulajdonságokon tovább lehetne még dolgozni, további kézzel készített tulajdonságot (*un. hand crafted features*) nyerhetnénk ki.

In [16]:
del df['genres'] 
del df['movie_imdb_link']
del df['plot_keywords']
del df['actor_3_name']
del df['actor_2_name']
del df['actor_1_name']
del df['movie_title']
del df['director_name']

# A végső DataFrame és ennek Numpy tömbbé való alakítása

A végső DataFrame a következő képp néz ki:

In [17]:
df

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,color_ Black and White,color_Color,language_English,language_OTHER,country_France,country_Germany,country_OTHER,country_UK,country_USA,content_rating_G,content_rating_OTHER,content_rating_PG,content_rating_PG-13,content_rating_R,Action,Adventure,Fantasy,Sci-Fi,Thriller,Romance,Animation,Comedy,Family,Musical,Mystery,Western,Drama,History,Sport,Crime,Horror,War,Biography,Music,Documentary,Film-Noir
0,537.685143,178.000000,0.000000,855.00000,1000.0,2.635383e+08,561872.209585,4834.000000,0.0,1570.36105,237000000.0,2009.000000,936.000000,7.9,1.78,33000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
1,302.000000,169.000000,563.000000,1000.00000,40000.0,2.635383e+08,471220.000000,48350.000000,0.0,1238.00000,300000000.0,2007.000000,5000.000000,7.1,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
2,537.685143,148.000000,0.000000,161.00000,11000.0,2.000742e+08,275868.000000,11700.000000,1.0,994.00000,245000000.0,2015.000000,393.000000,6.8,2.35,73733.924697,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
3,537.685143,164.000000,10010.626186,6453.27262,27000.0,2.635383e+08,561872.209585,68885.995525,0.0,1570.36105,250000000.0,2012.000000,15654.685353,8.5,2.35,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5,462.000000,132.000000,475.000000,530.00000,640.0,7.305868e+07,212204.000000,1873.000000,1.0,738.00000,263700000.0,2012.000000,632.000000,6.6,2.35,24000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
6,392.000000,156.000000,0.000000,4000.00000,24000.0,2.635383e+08,383056.000000,46055.000000,0.0,1570.36105,258000000.0,2007.000000,11000.000000,6.2,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
7,324.000000,100.000000,15.000000,284.00000,799.0,2.008073e+08,294810.000000,2036.000000,1.0,387.00000,260000000.0,2010.000000,553.000000,7.8,1.85,29000.000000,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,1,1,0,0,1,1,1,1,1,0,0,0,0,0,0,0,0,0,1,0,0
8,537.685143,141.000000,0.000000,6453.27262,26000.0,2.635383e+08,462669.000000,68885.995525,4.0,1117.00000,250000000.0,2015.000000,15654.685353,7.5,2.35,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
9,375.000000,153.000000,282.000000,6453.27262,25000.0,2.635383e+08,321795.000000,58753.000000,3.0,973.00000,250000000.0,2009.000000,11000.000000,7.5,2.35,10000.000000,0,1,1,0,0,0,0,1,0,0,0,1,0,0,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0
10,537.685143,178.189092,0.000000,2000.00000,15000.0,2.635383e+08,371639.000000,24450.000000,0.0,1570.36105,250000000.0,2016.000000,4000.000000,6.9,2.35,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
11,434.000000,169.000000,0.000000,903.00000,18000.0,2.000694e+08,240396.000000,29991.000000,0.0,1570.36105,209000000.0,2006.000000,10000.000000,6.1,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
12,403.000000,106.000000,395.000000,393.00000,451.0,1.683684e+08,330784.000000,2023.000000,1.0,1243.00000,200000000.0,2008.000000,412.000000,6.7,2.35,0.000000,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
13,313.000000,151.000000,563.000000,1000.00000,40000.0,2.635383e+08,522040.000000,48486.000000,2.0,1570.36105,225000000.0,2006.000000,5000.000000,7.3,2.35,5000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
14,450.000000,150.000000,563.000000,1000.00000,40000.0,8.928991e+07,181792.000000,45757.000000,1.0,711.00000,215000000.0,2013.000000,2000.000000,6.5,2.35,48000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0
15,537.685143,143.000000,0.000000,748.00000,15000.0,2.635383e+08,548573.000000,20495.000000,0.0,1570.36105,225000000.0,2013.000000,3000.000000,7.2,2.35,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
16,258.000000,150.000000,80.000000,201.00000,22000.0,1.416140e+08,149922.000000,22697.000000,4.0,438.00000,225000000.0,2008.000000,216.000000,6.6,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,0,1,0,0,1,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
17,537.685143,173.000000,0.000000,6453.27262,26000.0,2.635383e+08,561872.209585,68885.995525,3.0,1570.36105,220000000.0,2012.000000,15654.685353,8.1,1.85,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
18,448.000000,136.000000,252.000000,1000.00000,40000.0,2.410639e+08,370704.000000,54083.000000,4.0,484.00000,250000000.0,2011.000000,11000.000000,6.7,2.35,58000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
19,451.000000,106.000000,188.000000,718.00000,10000.0,1.790209e+08,268154.000000,12572.000000,1.0,341.00000,225000000.0,2012.000000,816.000000,6.8,1.85,40000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,1,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0
20,422.000000,164.000000,0.000000,773.00000,5000.0,2.551084e+08,354228.000000,9152.000000,0.0,802.00000,250000000.0,2014.000000,972.000000,7.5,2.35,65000.000000,0,1,1,0,0,0,1,0,0,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
21,537.685143,153.000000,464.000000,963.00000,15000.0,2.620307e+08,451803.000000,28489.000000,0.0,1225.00000,230000000.0,2012.000000,10000.000000,7.0,2.35,56000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
22,343.000000,156.000000,0.000000,738.00000,891.0,1.052197e+08,211765.000000,3244.000000,0.0,546.00000,200000000.0,2010.000000,882.000000,6.7,2.35,17000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0
23,509.000000,178.189092,0.000000,773.00000,5000.0,2.583554e+08,483540.000000,9152.000000,6.0,951.00000,225000000.0,2013.000000,972.000000,7.9,2.35,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
24,251.000000,113.000000,129.000000,1000.00000,16000.0,7.008352e+07,149019.000000,24106.000000,2.0,666.00000,180000000.0,2007.000000,6000.000000,6.1,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,1,1,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0
25,446.000000,178.189092,0.000000,84.00000,6000.0,2.180513e+08,316018.000000,7123.000000,0.0,1570.36105,207000000.0,2005.000000,919.000000,7.2,2.35,0.000000,0,1,1,0,0,0,1,0,0,0,0,0,1,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
26,315.000000,178.189092,0.000000,794.00000,29000.0,2.635383e+08,561872.209585,45223.000000,0.0,1570.36105,200000000.0,1997.000000,14000.000000,7.7,2.35,26000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
27,516.000000,147.000000,94.000000,6453.27262,21000.0,2.635383e+08,272670.000000,64798.000000,0.0,1022.00000,250000000.0,2016.000000,15654.685353,8.2,2.35,72000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
28,377.000000,131.000000,532.000000,627.00000,14000.0,6.517316e+07,202382.000000,26679.000000,0.0,751.00000,209000000.0,2012.000000,10000.000000,5.9,2.35,44000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
29,537.685143,124.000000,365.000000,1000.00000,3000.0,2.635383e+08,418214.000000,8458.000000,0.0,1290.00000,150000000.0,2015.000000,2000.000000,7.0,2.00,73733.924697,0,1,1,0,0,0,0,0,1,0,0,0,1,0,1,1,0,1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
30,537.685143,143.000000,0.000000,393.00000,883.0,2.635383e+08,522030.000000,2039.000000,0.0,1498.00000,200000000.0,2012.000000,563.000000,7.8,2.35,73733.924697,0,1,1,0,0,0,0,1,0,0,0,0,1,0,1,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
4930,91.000000,78.000000,56.000000,184.00000,376.0,2.882062e+06,5178.000000,1144.000000,2.0,101.00000,150000.0,2000.000000,346.000000,6.3,1.85,132.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4931,232.000000,85.000000,109.000000,18.00000,200.0,9.437933e+06,90827.000000,332.000000,0.0,329.00000,180000.0,2007.000000,96.000000,7.9,1.85,26000.000000,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
4933,29.000000,93.000000,0.000000,2.00000,58.0,1.559840e+05,586.000000,62.000000,0.0,9.00000,160000.0,2009.000000,2.000000,7.4,1.85,0.000000,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4936,277.000000,88.000000,365.000000,177.00000,383.0,3.085900e+07,96411.000000,1094.000000,0.0,826.00000,83532.0,1974.000000,371.000000,7.5,1.85,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4941,40.000000,91.000000,909.000000,42.00000,909.0,6.706368e+06,22800.000000,1048.000000,0.0,133.00000,160000.0,1989.000000,91.000000,7.5,1.66,667.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0
4955,31.000000,111.000000,589.000000,51.00000,589.0,1.017466e+07,12399.000000,916.000000,0.0,382.00000,100000.0,2006.000000,150.000000,6.7,1.85,0.000000,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0
4956,159.000000,81.000000,3.000000,7.00000,220.0,2.275782e+07,13521.000000,276.000000,0.0,150.00000,100000.0,2015.000000,40.000000,4.2,1.85,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4959,21.000000,81.000000,467.000000,287.00000,467.0,5.228617e+06,2770.000000,1431.000000,1.0,32.00000,100000.0,1987.000000,322.000000,7.0,1.85,471.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4962,88.000000,90.000000,56.000000,56.00000,126.0,1.105360e+05,4117.000000,284.000000,1.0,118.00000,40000.0,2001.000000,76.000000,7.0,1.85,0.000000,1,0,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0
4964,193.000000,88.000000,3.000000,307.00000,3000.0,5.937900e+04,12796.000000,4729.000000,3.0,52.00000,200000.0,2013.000000,982.000000,6.8,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,1,0,0,1,1,0,0,0,0,0
4971,241.000000,114.000000,29.000000,616.00000,956.0,3.272164e+07,67824.000000,3861.000000,0.0,279.00000,15000000.0,2009.000000,878.000000,6.6,1.85,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0
4973,138.000000,84.000000,0.000000,194.00000,1000.0,3.216970e+06,142619.000000,2065.000000,0.0,586.00000,60000.0,1998.000000,512.000000,7.5,1.66,24000.000000,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0
4975,32.000000,87.000000,0.000000,153.00000,1000.0,5.367670e+05,1622.000000,1362.000000,0.0,83.00000,60000.0,1998.000000,184.000000,5.3,1.85,30.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0
4977,193.000000,100.000000,293.000000,0.00000,0.0,1.152937e+07,85028.000000,0.000000,2.0,404.00000,65000.0,2004.000000,0.000000,7.3,1.78,0.000000,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0
4978,66.000000,82.000000,32.000000,128.00000,968.0,4.055700e+04,1389.000000,2046.000000,0.0,22.00000,60000.0,2011.000000,407.000000,5.6,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
4979,65.000000,82.000000,217.000000,442.00000,10000.0,3.008400e+04,5507.000000,11642.000000,3.0,23.00000,70000.0,2014.000000,969.000000,5.6,1.85,812.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4984,36.000000,98.000000,0.000000,73.00000,138.0,1.024660e+07,6375.000000,388.000000,0.0,36.00000,25000.0,1995.000000,111.000000,6.6,1.85,265.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4987,113.000000,98.000000,969.000000,433.00000,969.0,3.898040e+05,11816.000000,2530.000000,0.0,35.00000,65000.0,2010.000000,529.000000,6.3,2.35,0.000000,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4997,75.000000,90.000000,234.000000,15.00000,552.0,2.418160e+05,6246.000000,642.000000,0.0,76.00000,42000.0,2000.000000,61.000000,7.5,2.35,451.000000,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
4998,21.000000,90.000000,4.000000,113.00000,20000.0,2.772330e+05,2631.000000,20814.000000,5.0,26.00000,40000.0,1999.000000,467.000000,7.6,1.85,0.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5008,136.000000,102.000000,0.000000,216.00000,898.0,3.151130e+06,181749.000000,2103.000000,4.0,615.00000,230000.0,1994.000000,657.000000,7.8,1.37,0.000000,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0
5011,80.000000,97.000000,119.000000,7.00000,136.0,2.856622e+06,11550.000000,254.000000,0.0,197.00000,25000.0,1997.000000,108.000000,7.3,1.85,489.000000,0,1,1,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5012,233.000000,109.000000,453.000000,120.00000,1000.0,1.049997e+07,47502.000000,1458.000000,3.0,212.00000,35000000.0,2014.000000,206.000000,5.7,1.85,10000.000000,0,1,1,0,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
5015,61.000000,100.000000,0.000000,0.00000,5.0,1.227508e+06,15103.000000,5.000000,0.0,80.00000,23000.0,1991.000000,0.000000,7.1,1.37,2000.000000,1,0,1,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5025,73.000000,108.000000,0.000000,105.00000,462.0,1.804830e+05,16792.000000,760.000000,2.0,183.00000,10000.0,1973.316195,143.000000,6.1,1.37,0.000000,0,1,1,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,1,1,0,0,0,0,0
5026,81.000000,110.000000,107.000000,45.00000,576.0,1.360070e+05,3924.000000,776.000000,1.0,39.00000,4500.0,2004.000000,133.000000,6.9,2.35,171.000000,0,1,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0,0,0,0,0,1,0,0
5027,64.000000,90.000000,397.000000,0.00000,5.0,6.737800e+05,4555.000000,5.000000,0.0,26.00000,10000.0,2000.000000,0.000000,7.5,1.85,697.000000,0,1,0,1,0,0,1,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5033,143.000000,77.000000,291.000000,8.00000,291.0,4.247600e+05,72639.000000,368.000000,0.0,371.00000,7000.0,2004.000000,45.000000,7.0,1.85,19000.000000,0,1,1,0,0,0,0,0,1,0,0,0,1,0,0,0,0,1,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0
5035,56.000000,81.000000,0.000000,6.00000,121.0,2.040920e+06,52055.000000,147.000000,0.0,130.00000,7000.0,1992.000000,20.000000,6.9,1.37,0.000000,0,1,0,1,0,0,0,0,1,0,0,0,0,1,1,0,0,0,1,1,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0
5042,43.000000,90.000000,16.000000,16.00000,86.0,8.522200e+04,4285.000000,163.000000,0.0,84.00000,1100.0,2004.000000,23.000000,6.6,1.85,456.000000,0,1,1,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0

In [18]:
df.columns

Index(['num_critic_for_reviews', 'duration', 'director_facebook_likes',
       'actor_3_facebook_likes', 'actor_1_facebook_likes', 'gross',
       'num_voted_users', 'cast_total_facebook_likes', 'facenumber_in_poster',
       'num_user_for_reviews', 'budget', 'title_year',
       'actor_2_facebook_likes', 'imdb_score', 'aspect_ratio',
       'movie_facebook_likes', 'color_ Black and White', 'color_Color',
       'language_English', 'language_OTHER', 'country_France',
       'country_Germany', 'country_OTHER', 'country_UK', 'country_USA',
       'content_rating_G', 'content_rating_OTHER', 'content_rating_PG',
       'content_rating_PG-13', 'content_rating_R', 'Action', 'Adventure',
       'Fantasy', 'Sci-Fi', 'Thriller', 'Romance', 'Animation', 'Comedy',
       'Family', 'Musical', 'Mystery', 'Western', 'Drama', 'History', 'Sport',
       'Crime', 'Horror', 'War', 'Biography', 'Music', 'Documentary',
       'Film-Noir'],
      dtype='object')

In [19]:
df.describe()

,num_critic_for_reviews,duration,director_facebook_likes,actor_3_facebook_likes,actor_1_facebook_likes,gross,num_voted_users,cast_total_facebook_likes,facenumber_in_poster,num_user_for_reviews,budget,title_year,actor_2_facebook_likes,imdb_score,aspect_ratio,movie_facebook_likes,color_ Black and White,color_Color,language_English,language_OTHER,country_France,country_Germany,country_OTHER,country_UK,country_USA,content_rating_G,content_rating_OTHER,content_rating_PG,content_rating_PG-13,content_rating_R,Action,Adventure,Fantasy,Sci-Fi,Thriller,Romance,Animation,Comedy,Family,Musical,Mystery,Western,Drama,History,Sport,Crime,Horror,War,Biography,Music,Documentary,Film-Noir
count,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3.756000e+03,3756.000000,3756.000000,3756.000000,3756.000000,3.756000e+03,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000,3756.000000
mean,166.015905,109.725638,601.996458,640.305351,7406.460573,5.043835e+07,100332.183477,11085.969072,1.326430,320.545134,4.078590e+07,2003.198790,1912.653713,6.471539,2.107629,8482.525719,0.033014,0.966986,0.957934,0.042066,0.026890,0.021299,0.071885,0.084665,0.795261,0.023163,0.025293,0.150692,0.348243,0.452609,0.255325,0.207934,0.134984,0.132055,0.297391,0.228701,0.052183,0.388978,0.117678,0.025559,0.102236,0.015708,0.503994,0.039670,0.039404,0.188765,0.104366,0.040469,0.063632,0.062034,0.011981,0.000266
std,118.432258,19.981918,2043.676857,1058.512946,9856.429006,6.006620e+07,123690.030346,13858.899912,1.701272,325.937152,5.571417e+07,8.882217,3641.693500,1.034381,0.271143,16645.182220,0.178696,0.178696,0.200767,0.200767,0.161784,0.144399,0.258332,0.278419,0.403565,0.150441,0.157034,0.357796,0.476477,0.497815,0.436102,0.405883,0.341752,0.338596,0.457171,0.420052,0.222426,0.487583,0.322270,0.157837,0.302999,0.124361,0.500051,0.195208,0.194579,0.391374,0.305776,0.197082,0.244128,0.241250,0.108814,0.016317
min,2.000000,49.737632,0.000000,0.000000,0.000000,1.620000e+02,91.000000,0.000000,0.000000,4.000000,2.180000e+02,1973.316195,0.000000,3.296964,1.293985,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,77.000000,96.000000,11.000000,194.000000,745.000000,8.270233e+06,19667.000000,1919.750000,0.000000,110.000000,1.000000e+07,1999.000000,384.750000,5.900000,1.850000,0.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
50%,138.500000,106.000000,64.000000,436.000000,1000.000000,3.009311e+07,53973.500000,4059.500000,1.000000,210.000000,2.500000e+07,2004.000000,685.500000,6.600000,2.350000,227.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
75%,224.000000,120.000000,235.000000,691.000000,13000.000000,6.688194e+07,128602.000000,16240.000000,2.000000,398.250000,5.000000e+07,2010.000000,976.000000,7.200000,2.350000,11000.000000,0.000000,1.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,1.000000,1.000000,1.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
max,537.685143,178.189092,10010.626186,6453.272620,54303.159289,2.635383e+08,561872.209585,68885.995525,7.501069,1570.361050,7.241774e+08,2016.000000,15654.685353,9.300000,3.170077,73733.924697,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

És ennek a Numpy tömbjét -- amit a későbbiekben gépi tanuló algoritmusok tanításához fogunk használni --  így nyerhetjük ki, feltételezve, hogy az imdb_score érték az, amit tanítani szeretnénk:

In [20]:
X = df.loc[:, df.columns != 'imdb_score'].values
Y = df['imdb_score']

print(X.shape)
print(Y.shape)

(3756, 51)
(3756,)